#!/usr/bin/env bash
# update_baseline_pins.sh — refresh third_party/README.md commit-hash
# table from `git submodule status`, and write SHA-256 digests of every
# built binary into src/slackcertify/solvers/external_bin/CHECKSUMS.
#
# Usage:
#     bash scripts/update_baseline_pins.sh
#
# Run this after a successful `scripts/install_baselines.sh`.

set -euo pipefail

REPO_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
THIRD_PARTY_DIR="${REPO_ROOT}/third_party"
BIN_DIR="${REPO_ROOT}/src/slackcertify/solvers/external_bin"
README="${THIRD_PARTY_DIR}/README.md"
CHECKSUMS="${BIN_DIR}/CHECKSUMS"

log()  { printf '\033[1;34m[update-pins]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[update-pins]\033[0m %s\n' "$*" >&2; }
fail() { printf '\033[1;31m[update-pins]\033[0m %s\n' "$*" >&2; exit 1; }

sha256_of() {
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum "$1" | awk '{print $1}'
    elif command -v shasum >/dev/null 2>&1; then
        shasum -a 256 "$1" | awk '{print $1}'
    else
        fail "neither sha256sum nor shasum is available"
    fi
}

# 1. Resolve commit hashes via `git submodule status`.
#    Output looks like:
#         abcdef1234... third_party/EECBS (heads/main)
#    The leading character is " ", "+", or "-".
declare -A COMMIT_OF
log "reading commit hashes from git submodule status"
while IFS= read -r line; do
    [[ -z "${line}" ]] && continue
    cleaned="${line# }"; cleaned="${cleaned#+}"; cleaned="${cleaned#-}"
    sha="$(printf '%s' "${cleaned}" | awk '{print $1}')"
    path="$(printf '%s' "${cleaned}" | awk '{print $2}')"
    COMMIT_OF["${path}"]="${sha}"
done < <(cd "${REPO_ROOT}" && git submodule status)

# 2. Patch third_party/README.md in place.
if [[ -f "${README}" ]]; then
    log "patching commit hashes into ${README}"
    today="$(date -u +%Y-%m-%d)"
    tmp="$(mktemp)"
    cp "${README}" "${tmp}"
    for sub in EECBS lacam lacam_star pibt2 btpg; do
        path="third_party/${sub}"
        sha="${COMMIT_OF[${path}]:-TODO_PIN_COMMIT_HASH}"
        if [[ "${sha}" != "TODO_PIN_COMMIT_HASH" ]]; then
            short="${sha:0:12}"
            # Replace the TODO placeholder on the row referencing this submodule.
            python3 - <<PY "${tmp}" "${path}" "${short}" "${today}"
import re, sys
fp, path, short, today = sys.argv[1], sys.argv[2], sys.argv[3], sys.argv[4]
with open(fp, encoding='utf-8') as fh:
    text = fh.read()
pattern = re.compile(
    r'(`' + re.escape(path) + r'`[^|]*\|[^|]*\|\s*)`TODO_PIN_COMMIT_HASH`'
)
text = pattern.sub(r"\1`" + short + "`", text, count=1)
text = text.replace(
    f"`{path}`", f"`{path}`",  # no-op; placeholder for future "last build" patch
)
with open(fp, 'w', encoding='utf-8') as fh:
    fh.write(text)
PY
        else
            warn "no commit recorded for ${path}; leaving placeholder"
        fi
    done
    mv "${tmp}" "${README}"
fi

# 3. Write CHECKSUMS file with the SHA-256 of every built binary.
mkdir -p "${BIN_DIR}"
log "writing ${CHECKSUMS}"
{
    printf '# Generated by scripts/update_baseline_pins.sh on %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    printf '# format: <sha256>  <binary_name>\n'
    for name in eecbs lacam lacam_star pibt btpg; do
        file="${BIN_DIR}/${name}"
        if [[ -f "${file}" ]]; then
            printf '%s  %s\n' "$(sha256_of "${file}")" "${name}"
        else
            printf '# %s missing\n' "${name}"
        fi
    done
} >"${CHECKSUMS}"

log "done."
